import styles from "./chapter.module.css";
import PaginatedReader from "./PaginateReader.tsx";
import Link from "next/link";


const LOREM = `Az a rengeteg ember, aki a Földön él, vajon okkal született, céllal, vagy mindez tényleg csak a véletlen műve? Az emberek gyakran elgondolkodnak azon, vajon szerencsés véletlen, amikor egy cserép néhány centivel melléjük zuhan a járdán, vagy amikor hirtelen megállnak az út szélén, és az autó nem üti el őket. Olykor erős késztetést éreznek, hogy megtegyenek vagy kimondjanak valamit, amit nem is akarnak igazán. Máskor pedig épp az ellenkezőjét teszik: egy figyelmeztető hang azt suttogja belülről, hogy ne tegyék, ám ők mégsem engednek. Az igazság az, hogy ezek egyike sem véletlen. Ezek a hangok, késztetések a mi sugallataink. Mi, őrangyalok, a Menny harcosai, láthatatlan árnyékként követjük a ránk bízott személyeket. A jelenlétünk nem mindenki mellett állandó. Akad, akit folyamatosan őrzünk. Mások életében csak időszakos vendégek vagyunk. Azért, mert odafent így rendelik el. Egyesek újoncok a szolgálatban, mások évezredek óta védelmezik a halandókat. Minden sors egy nagyobb terv része, és a mi  feladatunk annak biztosítása, hogy védenceink végigjárják az utat, ami meg van írva számukra. Minden összefügg mindennel, még ha az emberek nem is látják a teljes képet. És ott van a szabad akarat is – az a fránya kiskapu, ami lehetőséget ad nekik, hogy saját döntéseket hozzanak. Néha viszont éppen ezzel okoznak nekünk komoly fejfájást.  Ezért figyeltem a védencemet, San Francisco egy kis kávézójának hátsó sarkában. Az asztalokat gyertyafényes lámpák díszítették 
– bár a verőfényes délután során éppen nem világítottak –, mellettük üvegvázában álltak a friss tulipánok. A falakon régi fényképek idézték a kávézó múltját, a közösség emlékeit, miközben a kényelmes székek és kanapék a nyugodt olvasást és beszélgetéseket biztosítják. Én az egyik boksz kanapéján heverésztem, fekete bakancsos lábam az előttem lévő szék támláján pihent. A lábamra simuló kék farmerban, bézs trikóban és fekete bőrdzsekiben könnyedén beleolvadhatnék a tömegbe, ha azt akarnám, hogy meglássanak. De én most megfigyelek. Láthatatlanul felmérem a terepet. Ha valaki ide ülne, ahol vagyok, nem érezne semmi változást. Néhány vendég mellett ott állt a hozzájuk rendelt őrangyal. Amikor észrevettek, egyszerűen csak felém bólintottak, majd visszafordultak a védencükhöz. Ez a világ rendje. Mi csendes megfigyelők vagyunk, és többnyire azok is maradunk. Azon töprengek, vajon hová tűntek az emberek közötti, órákig tartó beszélgetések. Egyre többen merülnek a telefonjukba, még egy mosolyt sem ejtve a pultos felé. 
Néhány évtizede az embereknek még volt idejük egymásra. Akkor nekünk is kevesebb dolgunk akadt. Régen még képesek voltak úgy belemerülni a beszélgetésbe, hogy az idő fogalma is elveszett számukra. Ma, a földi dátum szerint 2024-ben, az élet egy folyamatos rohanásból áll: munkából edzésre, edzésről vásárolni, majd haza, ahol a telefonok és a képernyők töltik ki a maradék szabad perceket. A közösségi oldalak elhitették velük, hogy összekapcsolják őket, miközben inkább egyre távolabb sodródnak egymástól, mert megszűnnek a személyes kapcsolatok. Az utcán mindenki siet, senki sem áll meg egy pillanatra, hogy élvezze a naplementét, vagy csak úgy, elbeszélgessen egy ismeretlennel. Noha egy gyors „hogy vagy?” elhangzik néha, a válasz már senkit sem érdekel igazán. És ahogy minden gyorsabbá válik, valójában mindenki egyre magányosabb lesz. Egy órája pihentem mozdulatlanul, amikor végre megpillantottam egy ismerős őrangyalt. Felálltam és odaléptem Astorhoz, aki egy frissen érkezett vendéget kísért. Ritkán van lehetőségünk hosszabb időt tölteni egymással, hiszen a védenceinket nem hagyhatjuk magukra. Ha a védencünk más, állandó védelmet élvező emberek társaságában tölti az idejét, akkor mi, őrangyalok is lazíthatunk egy kicsit. De ezt előre sohasem tudhatjuk, és legtöbben emiatt már nem is igénylik a társaságot. Astor is ilyen. Magának  való, csendes megfigyelő, ahogy a többségünk is az. Mondjuk engem ez sosem tartott vissza attól, hogy megpróbáljak kicsikarni belőle egy-két mondatot. Nem mintha könnyű dolgom lenne. Egy gyors mozdulattal felugrottam a mellette lévő bárszékre. A forgószék éppen vele szembe fordult, miközben egyenesen a szemébe néztem.
– Hogy alakulnak a dolgok nálatok? – kérdeztem. Felém se nézett, válasza tömör és lényegre törő volt. – Jól.
– Eh, régi barátként se vagy hajlandó szóba állni velem? Még az ellenségeimmel is tartalmasabb beszélgetéseim vannak… – húztam vigyorra a szám. Felvonta szemöldökét, majd halványan elmosolyodott.
– Azért, mert túl sokat dumálsz. Mit akarsz tudni?
– Semmi konkrétat. Esetleg egy jó kis pletyka?
– Ti nők, mindegy, hogy emberként vagy angyalként léteztek, mindig csak pletykáltok – csóválta fejét, szája sarkában halvány mosollyal. – Az utóbbi időben egyre erősebb a démoni jelenlét. Te is érzed?
– Hogy érzem-e? A héten már kétszer is megpróbálták megkörnyékezni Mattet.
– És mi lett velük?
– Szerinted? – vontam meg a vállam vigyorogva. Astor felsóhajtott.
– Tudod, hogy el kell őket fogni, jelenteni, aztán kihallgatni.
– De abban nincs semmi izgalom – feleltem. – Meg különben is, annyira felbosszantanak, hogy nem tudok leállni… – mondtam vigyorogva, ami azért nem fedte az igazság minden szeletét. Igazából énem egy része nem akarta elengedni a démonokat, amelyek megpróbálták befolyásolni védencemet. Láttam rajta, hogy nem ért egyet a módszeremmel, de szó nélkül hagyta. Egy biccentéssel a védence felé intett, aki éppen a baristával próbált flörtölni.
– Nekem is jobban nyitva kell tartani a szemem. Az utóbbi időben többször is próbáltak hatni rá. Nem lenne szerencsés, ha sikerülne nekik. Állítólag még sokra viheti – mondta.
– Nem hiszem, hogy komoly a támadás. A démonok mindig aktívak. Ez a dolguk.
– Talán. De mintha most felkészültebbek lennének. Mindegy. Na és ki az a bájgúnár veled? – váltott témát hirtelen. Mattre pillantottam. A székén ült hátradőlve, nyitott könyvvel a kezében, de már percek óta nem lapozott. Sötétbarna haja kócosan meredt az égnek, kék szeme mereven a lapokra szegeződött, mintha teljesen kizárná a külvilágot. Bár egyszerű, hétköznapi ruhát viselt – farmer, fekete, kapucnis pulcsi –, mégis képes volt a testbeszédével távol tartani az embereket, és az egész világról tudomást sem venni. Valahogy lenyűgözőnek találtam ezt a képességét. Ugyan csak egy hete voltam mellette, éreztem, hogy valami nincs rendben vele, csak még nem sikerült rájönnöm,  hogy mi. Nem akartam megerősíteni Astort, de tényleg nem megszokott, hogy hetente többször is a védencünk közelébe férkőznek. Ráadásul néha úgy éreztem, Mattnek van egy sötét oldala is, amit valahogy még előlem is eltitkolt. De erről nem akartam beszélni a szaktársammal, így végül csak megrántottam a vállam.
– Semmi jelentős – feleltem végül. – Csak az új védencem. – Astor összevonta a szemöldökét.
– Elég szokatlan, nem gondolod? Téged ennél sokkal komolyabb feladatokra szoktak beosztani. – Elmosolyodtam.
– Miért? Jobb egy pökhendi, negyvenes politikust követni, mint egy egyetemista srácot?
– Erre te is tudod a választ – mondta, majd felállt, és elindult a védence után. Figyeltem, ahogy követte, aztán visszatelepedtem Matt mellé. Miért bízták rám ezt a fiút? Általában csak olyanokat védek, akik fontos szerepet töltenek be a világban. Matt egyáltalán nem tűnik különlegesnek. Vagy talán tévedek? A korábbi megbízásaim egytől egyig komoly figyelmet igényeltek. Általában olyan emberek mellé osztottak be, akiknek a tevékenysége sorsfordító volt, vagy épp komoly veszély leselkedett rájuk. A kettő pedig általában kéz a kézben járt. Politikusok, vállalkozók, igazgatók, rendőrök, vallási vezetők – mindannyian különböző életutat jártak be, de egy dologban hasonlítottak: nagy változásokat hoztak vagy hozhatnak a világba. Én pedig általában akkor kaptam meg őket, amikor már forró volt a talaj a lábuk alatt. A fiatal lelkekkel mindig csak baj van. Nem érzik a veszélyt, feszegetik a határaikat. Mellettük állandó készültségben kell lennünk, nehogy rossz útra tévedjenek. Ahelyett, hogy a valóban fontos dolgokra koncentrálnék, minden erőmmel azon kell lennem, hogy megakadályozzam a meggondolatlan cselekedeteiket. Fogalmam sincs arról, hogy miért éppen őt kaptam. A misszió részleteit mi magunk sem ismerjük. Mindig csak a következő célfeladatot kapjuk meg. Ez a fiú – bár a maga rejtélyes, sötét módján, határozottan helyesnek tűnik – az elmúlt egy hétben semmilyen különleges képességet nem mutatott, ami folyamatos felügyeletet indokolna. Persze, egy-két furcsa eseményt leszámítva. De ki vagyok én, hogy megkérdőjelezzem a főnök döntését? Csak hát, néha igazán beavathatna a terveibe. Nem nagy dolog, csak hogy ne érezzem magam úgy, mint aki sötétben tapogatózik a védence mellett, aki talán veszélyesebb, mint elsőre látszik.
Mélyen magamba szívtam a kávézó fahéjjal és gőzölgő tejjel átitatott illatát, és elgondolkodtam. Milyen szívesen megkóstolnám őket. Oly rég volt, hogy ilyen finomságokkal kényeztethettem magam. Ritkán, néhány évente – inkább százévente – lehetőséget kapunk arra, hogy úgymond, szabadságra menjünk. Ilyenkor emberként élhetünk egy rövid ideig, hogy megtapasztaljuk, milyen is valójában halandónak lenni, és ne csupán külső megfigyelőként létezzünk. Elvileg így jobban tudunk azonosulni a védenceinkkel is, de már azt sem tudom, mikor voltam utoljára a másik oldalon. Azt hiszem, a lazább megbízatások után néhány napig emberi alakban éltem. Egy jó étkezés, egy séta a parton, egy rövid beszélgetés idegenekkel – apró pillanatok, amik emlékeztetnek arra, milyen az emberek világa. De amint lemegy a nap, újra önmagammá válok, és visszatérek szokásos feladataimhoz.
*
Így válhattam az egyik legjobb angyallá.
Így válhattam az egyik legjobb katonává.
Az én feladatom, hogy életben tartsam a rám bízott személyt, a jó úton vezessem, és sugallataimmal segítsem, hogy beteljesítse a sorsát.
Két fő szabály létezik, amit soha, semmilyen körülmények között nem szeghetsz meg:
1.      A védencednek életben kell maradnia.
2.      Soha nem érintheted meg, és nem találkozhatsz vele fizikailag.
Ennyi. Egyszerű, nem?
Legalábbis én így hittem… egészen addig, amíg meg nem történt az, aminek soha nem lett volna szabad megtörténnie. Kiléptem a kávézóból az utcára, és azonnal megéreztem a Matthew-ból áradó feszültséget. Dühöt, csalódottságot. Nem tudtam, honnan erednek az érzései, vagy mire irányulnak, de egyvalamiben biztos voltam: jót tenne neki, ha kiszellőztetné a fejét. Megpróbáltam sugalmazni, hogy sétáljon egyet. Súgtam – és vártam. Nem kényszeríthetem semmire. Ha nyitott a gondolatra, amit küldtem neki, talán megfogadja. A döntés mindig az övé. Szerencsére most hajlott rá, így végül a hosszabb úton indult el. A tengerpart felé haladva körbepillantottam, és el kellett ismernem: ez a város igazán kellemes. A tenger nyugtató morajlásával, a homokos partjaival, a színes halászcsemegék és a friss tengeri levegő egyedi illatával, amit már messziről is megérzel. Az utcán egy kissé elhanyagolt külsejű férfi jött velünk szembe. Több réteg ruhát viselt, amit helyenként lyukak tarkítottak. Fejét lehorgasztva bámult maga elé, miközben úgy sétált, mintha minden mozdulat fájdalmat okozna neki. Matthew is észrevette. Próbált távolabb húzódni, amikor a férfi felkapta a fejét, és egyenesen rám nézett.
– Ez az egész miattatok van! – morogta ujjával felém bökve, majd elém köpött. A nyálcsepp Matthew lába előtt ért földet, mintha egyenesen rá mutatna. Kedves – gondoltam magamban, miközben fogalmam sincs, ki ez az ember, és miről beszél.
– Hé, ember, neked meg mi bajod van?! – kiáltott fel Matthew meglepetésében egy lépést hátrálva. Az igazság az, hogy vannak emberek, akik látóként ismertek – képesek érzékelni minket, sőt, kommunikálni is velünk. Legtöbbjük valahogy belekeveredik a világunkba, és akár segíthet is a küldetésünk teljesítésében. De ezt az embert még soha nem láttam.
– Jobb, ha távol tartod magad a bajtól, kölyök – mondta a férfi, majd vállon lökte Matthew-t, és folytatta útját. Matt kihúzta magát, és egy pillanatig azt hittem, hogy utánaindul, de csak a fejét csóválta értetlenül. Néhány másodpercig a távolodó férfit nézte, igyekezett úrrá lenni a zavarodottságán, mielőtt ő is a dolgára megy. 
Az utcán egymás után sorakoztak a kiülős kávézók, ahol az emberek kellemesen beszélgettek, iszogattak, napozgattak. Az anyaépületek élénk színekben pompáztak, ablakaikat és erkélyeiket virágokkal díszítették, miközben illatuk beborította az utcát kétoldalt szegélyező pálmafákat. Egy másik életben akár még el is tudnám képzelni, hogy itt éljek. Matthew nyugtalansága azonban e színes kitérő ellenére sem csillapodott. Folyamatosan hátra kellett pillantania, mintha úgy érezné, valaki követi. Ekkor hirtelen megcsapta az orromat az a kesernyés, füstös bűz, ami a démonok jelenlétét jelzi. Meglepett, hogy ő is képes érzékelni őket, ráadásul ilyen erősen. Próbáltam felmérni a járókelőket, de bárhogy erőlködtem, nem láttam semmi gyanúst. Rossz érzésem egyre erősödött, és ez semmi jót nem jelentett. Közelebb húzódtam Matthew-hoz, már majdnem megérintettem. A fülébe suttogtam, próbáltam enyhíteni a benne tomboló feszültséget, de mintha meg sem hallott volna. Minden erőmmel igyekeztem megnyugtatni, csak rá koncentrálni, amikor egy újabb, szörnyű bűzhullám csapta meg az orromat. Ekkor valaki hátulról elkapta a nyakamat, és fojtogatni kezdett. Reflexből megragadtam a karját, a szabad kezemmel pedig hátra, az arcába könyököltem. Erre felnyögött, szorítása meggyengült. Egy pillanatig sem hezitáltam: a lendületet kihasználva átdobtam a vállamon. A démon tompa puffanással csapódott a földre, hogy egyetlen hátborzongató, ruganyos mozdulattal talpra ugorjon, kissé meghazudtolva a gravitációt. Felismertem ezt az arcot. Amikor megszólalt, minden kétségem elszállt. – Mondtam, hogy még találkozunk, angyalka.
– Nézd csak, mit böfögött fel a pokol pöcegödre?! – vigyorodtam el gúnyosan. – Hátulról támadsz? Ráadásul megfigyelés közben? Nem változtál semmit. És te magad jöttél fel személyesen? Segíts már, mikor is találkoztunk utoljára? – szegeztem a kérdést Reavennek, a démonok egyik parancsnokának. Vérszomjas szadista, aki élvezetét leli az emberek kínzásában. Nem véletlenül jutott el idáig. 
És most itt állt előttem, mosolyogva.
Még kezdő angyal koromban ismertem meg, első küldetéseim egyikén. Egy kis faluban szórakozott, azaz a helyiek  életkilátásait rombolta úgy, hogy felerősítette félelmeiket ésmás negatív érzéseiket, csak mert, ahogy ő fogalmazott, éppen „unatkozott”.
– Annak száz éve is már. Egész kikupálódtál. Erre a könyökösre nem számítottam.
– Ha tudtam volna, hogy te vagy az, erősebbet csapok. Már csak a régi szép idők emlékére is. Mi dolgod errefelé? Nem hiszem, hogy puszta nosztalgiából estél nekem. – Reaven szélesen elvigyorodott, de a szeme hidegen csillogott.
– Neeem, dehogy. Csak épp erre jártam, és pont megláttalak. És mondom…
– Persze – felhorkantam. – A környéken nincsenek olyan horderejű dolgok, hogy te csak úgy erre kószálj. Pláne egyedül. A mondandód ugyanúgy bűzlik, mint te magad, és hidd el, az elég durva. Körülbelül olyan, mint a többnapos tornazokniba tekert sajt, ami a napon rohad egy haltetem tetején. – Reaven nem reagált, csak halványan elmosolyodott. Kezdett gyanússá válni. Körbenéztem, de nem láttam a csatlósait. – A kutyáid merre vannak? Sosem járkáltok egyedül, pláne nem egy parancsnok. – Figyeltem az arcát, de a vonásai rezzenéstelenek maradtak. – Várjál… fordulj csak meg! – Köröztem a kezemmel az arca előtt, hogy egy kis nyomatékot adjak a szavaimnak, de ő csak állt mozdulatlanul. Gyorsan mögé léptem, mire ő is azonnal megfordult, szemében árnyalatnyi élvezettel. – Különös.  Azt hittem, mindig ott lihegnek a nyomodban… – pillantottam körbe színpadiasan. – …csak nem beijedtek, ahogy padlót fogtál az előbb? – Reaven lassan felhúzta a szemöldökét, és villantott egy félmosolyt.
– De felvágták a nyelvedet. Csak nem provokálni próbálsz?
– Ugyan, Reaven – billentettem oldalra a fejem. – A te fajtád már egy félreérthető pillantásra is vérben forgó szemekkel ugrik. De te? Most csak állsz itt, és fecsegsz. Nem így ismertelek meg. Ráadásul a pincsijeid nélkül. – Öszszeráncoltam a szemöldököm, és oldalra kaptam a tekintetem. Matthew egyre jobban távolodott tőlem, már az utca végéhez ért. Két oldalán démonok kísérték, szorosan mellette lépkedve. Biztos az említett pincsik.
Szóval Matthew miatt van az egész. Sejtettem. De vajon mit akarnak tőle? Bármi is legyen a céljuk, működik. Látom és érzem, ahogy egyre mélyebbre süllyed a fájdalom és kétségbeesés mocsarába. Mintha valami belülről tépné szét. Milyen nagyszerű dolog is őrangyalnak lenni. Nem kell saját érzésekkel és fájdalommal törődni, a másiké épp elég, hogy darabokra szedjen. De nem hagyhatom, hogy a démonok magukkal rántsák. Ki kell hoznom ebből.
– Tudod, mindig öröm veled találkozni, pláne, ha felmoshatom veled a padlót – vigyorodtam el gúnyosan. – De sajnos nincs időm a frappáns, magasröptű dumádat hallgatni. – Megfordultam, hogy Matthew felé induljak, de két  démon egyetlen szempillantás alatt ott termett mellettem. Acélos ujjaik a karomra fonódtak, és egy mozdulattal viszszafordítottak Reaven felé. – Mi a franc? – mordultam fel, és megpróbáltam kirángatni magam, de a szorításuk nem engedett. Mintha fémbilincsek tartanának fogva. Reaven szórakozottan elmosolyodott.
– Itt vannak a pincsik, akiket hiányoltál. – Két lépést közelebb jött. – Pontosabban egy részük. A másik kettő épp felszínre hozta a fiúcskád legnagyobb félelmeit és kétségeit. – A démon öklének első csapása megcsavarta a gyomrom, csakúgy, mint a hangjából sugárzó elégedettség. A következő ütés szinte kettészakított. A harmadik már nemcsak a tüdőmből szorította ki a levegőt, hanem egy pillanatra elsötétítette a világot is. Megremegett a térdem. – Ez a legjobb rész – jegyezte meg Reaven élvezettel, miközben összeszedtem magam. Mielőtt teljesen kiegyenesedhettem volna, újra lecsapott. Már számítottam rá. A gyomromba vágott ököl kiszoríthatta volna belőlem a lelket, de megfeszítettem a hasfalamat.
– Ennyire telik? Ketten lefognak, te meg püfölsz? Hol marad a jó öreg szemtől szemben?
– Ha néhány hétig kezelésbe vennélek, tanulhatnál egy kis jó modort – jegyezte meg a szórakozott, kegyetlen hangon. Düh fortyogott bennem, forró parázsként égette bőrömet. De a mélyben ott lüktetett Matthew is. Horkanások szakadtak fel belőlem, vadul rángattam magam a katonák szorításában. Nem a legelegánsabb megoldás, de legalább lekötötte a figyelmüket. Csakhogy Reavent nem lehetett megzavarni. Az ökle újra ütésre lendült, és egy pillanattal később a vér fémes ízét éreztem a számban. A fejem enyhén oldalra billent, arcom és az állkapcsom lüktetett a találat nyomán.
– Értesz te bármit is ebből az egészből? Tudod egyáltalán, miért vagyunk itt? – kérdezte. Rángattam a karjaimat, ahogy csak tudtam. A balomon álló fickó Reavenre pillantott. Megvan.
– Mondd csak, te tudod mit cselekszel, vagy most is csak bólogatva engedelmeskedsz, mint egy kiskatona? – A düh fellángolt bennem, égetett belülről. De nem hagyhattam, hogy eluralkodjon rajtam. Először szabadulnom kell, utána törődhetek azzal, hogy szétszedjem ezt a rohadékot. Mindent beleadtam. A balról álló démon szorítása végre engedett, így nem haboztam. Súlypontomat a jobb lábamra helyeztem, és bal térdemmel erőteljes rúgást küldtem a térdhajlatába. Reccsenés hallatszott, a démon felhördült, majd térdre rogyott. Kihasználva pillanatnyi előnyömet, kirántottam karom a szorításából, és azonnal a bal térdemre erősített tőrért nyúltam. Egyetlen lendülettel sújtottam le. A penge a kis rohadék állkapcsa alá fúródott, majd végigcsúszott az agyáig. Az ujjaim kiszabadultak a szorításából. Kirántottam a tőrt, megpördültem, és mielőtt a másik démon feleszmélhetett volna, teljes erőből a mellkasába 
döftem a pengét. Pontosan a szívébe. Vagy abba a rohadó valamibe, ami egykor a szíve lehetett. Mindketten a földre zuhantak. Kifulladtam, de nem álltam meg. Rávicsorogtam Reavenre, és közelebb mentem. Olyan közel, hogy az arcunk szinte összeért. Az ujjaim még mindig a tőr markolatán pihentek, és nehezemre esett fékezni magam. Ő viszont csak vigyorgott.
– Mindig is tisztességtelen módon játszottál – jegyeztem meg kéjesen.
– Gondolkozz, angyalka. – Reaven vigyorogva hátrálni kezdett, kezét védekező állásba emelte, mintha a következő csapásom várná. A testem már támadásra indult, de valami visszatartott. Egyik felem tudni akarta, mi a fenéről beszél. Egyértelmű, hogy itt valami nagyon nincs rendben. Másik felem viszont – mély, zsigeri ösztönből – azt súgta: ezen ráérek később is rágódni. Inkább rohanj! Most! Megfordultam, és teljes erőből sprintelni kezdtem Matthew felé – vagyis abba az irányba, ahol utoljára láttam. Az utca végére érve azonban ő már nem volt sehol. A távolból még hallottam, ahogy Reaven utánam üvölt, de a szavai már elvesztek a zihálásom, és a fülemben dübörgő szívverésem zajában. Vajon mire célozhatott? Futottam, ahogy csak bírtam. A mellkasom minden egyes lépésnél égetett, de nem állhattam meg. Hogy lehettem ilyen felelőtlen? Hagytam, hogy Reaven feldühítsen, és ezzel elérte, amit akart. Elterelte a figyelmemet. Azonnal Matthew után kellett  volna rohannom. A gondolatok egymásba gabalyodtak a fejemben, miközben elértem a sarkot, ahol befordultam. Megláttam a fiút. A világ egy pillanatra megállt, ahogy a jelenet kibontakozott előttem. Védenceim még soha nem kerültek veszélybe – legalábbis nem az én felügyeletem alatt. De most… ahogy ott állt, a démonok gyűrűjében… Az agyam kiadta a parancsot, hogy mozduljak, de a testem egy tizedmásodpercre lefagyott. Már túl késő volt. Szívem a torkomban dobogott, fülem zúgott, izmaim megfeszültek. Gondolkodás nélkül cselekedtem. Matthew alvajáró módjára sétált tovább, mint aki nincs tudatában annak, hogy hol van. Nem nézett körbe, nem adta jelét sem, hogy érzékelné a környezetét. Csak ment egyenesen az úttest felé. Egy busz közeledett balról. Dübörgő motorhangja egyre erősödött, de Matthew nem lassított. A két démon, akik eddig kísérték, felszívódtak. Elvégezték a feladatukat. A szívem dühösen kalapált, a tüdőm égett, és minden erőmet beleadtam, hogy elérjem. Már a sugalmazás sem használt. Üzenetem a semmibe porladt. Nem hallotta meg. Nem is láthatott. Mintha valami más, valami erősebb tartaná a markában.
–Matthew! – kiáltottam könyörgő hangon, szinte sikoltva. – Állj meg! – Semmi reakció. A buszsofőr viszont észrevette őt. A jármű dudájának tompa üvöltése hasította ketté a levegőt, miközben kerekei hangos csikorgással csúsztak az aszfalton. De a busz túl nagy lendülettel jött.  Matthew nem reagált semmire. Egyetlen másodpercem maradt.
Az utolsó esély.
A végén már nem is a lábam vitt előre, hanem valami tiszta, nyers ösztön. Egyetlen pontra szűkült a világ: Matthew-ra. A pillanatra, amikor elérhetem. Maradék erőmet összeszedve elölről nekirontottam, és hátralöktem. Az ütközéstől megtántorodott, és hátrálni kezdett. Egy… kettő… három lépés. Egyensúlya megbillent, és éreztem, hogy eleshet. Elkaptam, mielőtt elvágódott volna, ujjaim görcsösen szorították a vállát.
A szemébe néztem.
A felismerés egyszerre hozott magával megkönnyebbülést… és jeges döbbenetet.
Mert abban a pillanatban, amikor felfogtam, hogy megmentettem az életét, már tudtam.
Hogy ezt igazán, istentelenül elcsesztem.`;

export default function FirstChapterPage() {
  return (
    <div className={styles.main}>
      <div className={styles.bookMain}>
        <h1 className={styles.title}>Az első fejezet</h1>

        <PaginatedReader text={LOREM} storageKey="chapter-1-page" />
                  <Link
                    className={styles.lightButton}
                    href={"https://alomgyar.hu/konyv/eg-es-fold-kozott"}
                  >
                    Megrendelés
                  </Link>
      </div>
    </div>
  );
}
